name: "eCabinet"
version: "0.0.1"
slug: domiot_ecabinet
description: Un serveur REST pour la gestion des items du placard connecté
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options: {}
schema: {}
ports:
  8080/tcp: 8001 # Port sur lequel l'API FastAPI écoutera
services:
  - mqtt:need